In [1]:
import numpy as np

In [38]:
matrix_array = np.arange(1, 51).reshape(10,5)
matrix_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

## Generate 5 random positions and fill up those postions with -100

In [39]:
# Generate 5 random positions
fault_values_positions = np.random.randint(0, 10, size=(5, 2))

# column values should be below 5
fault_values_positions[:, 1] = np.random.randint(0, 5, size=5)
fault_values_positions

array([[0, 2],
       [3, 3],
       [0, 0],
       [6, 4],
       [1, 1]])

In [41]:
# Filling up those random positions with -100
for positions in fault_values_positions:
    matrix_array[positions[0], positions[1]] = -100

matrix_array

array([[-100,    2, -100,    4,    5],
       [   6, -100,    8,    9,   10],
       [  11,   12,   13,   14,   15],
       [  16,   17,   18, -100,   20],
       [  21,   22,   23,   24,   25],
       [  26,   27,   28,   29,   30],
       [  31,   32,   33,   34, -100],
       [  36,   37,   38,   39,   40],
       [  41,   42,   43,   44,   45],
       [  46,   47,   48,   49,   50]])

## Creating A Masked Matrix

In [44]:
# Creating A Masked Matrix

masked_matrix = np.ma.masked_where(matrix_array == -100, matrix_array)

masked_matrix

masked_array(
  data=[[--, 2, --, 4, 5],
        [6, --, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, --, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, --],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]],
  mask=[[ True, False,  True, False, False],
        [False,  True, False, False, False],
        [False, False, False, False, False],
        [False, False, False,  True, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False,  True],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],
  fill_value=999999)

In [45]:
# Fill The blanks with (0)

masked_matrix = masked_matrix.filled(0)
print(masked_matrix)

[[ 0  2  0  4  5]
 [ 6  0  8  9 10]
 [11 12 13 14 15]
 [16 17 18  0 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34  0]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
