In [1]:
import numpy as np


In [3]:
# generate a vector (list) from 0 to 9

data = np.arange(0, 9)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# another version, third parameter is step size, this
# generates a list of even numbers between 0 and 10
data = np.arange(0,11,2)
data

# arange() does not have a matrix version of itself (there's another
# way though) (reshape, which we'll cover later)

In [ ]:
#converting python data to numpy arrray

import numpy as np

numbers = [3, 5, 6, 2]
data = np.array(numbers)

In [ ]:
# vector, 1 dimension
# convert python list to numpy array (vector)

numbers = [3, 5, 6, 2]
data = np.array(numbers)
data

In [13]:

# matrix, 2-dimensional
day_1 = [18, 19, 17, 21]
day_2 = [15, 14, 15, 17]
day_3 = [9, 10, 9, 8]
temperatures = [day_1, day_2, day_3]
# convert list of lists to matrix, 2 2-dimensional
data= np.array(temperatures)
data


array([[18, 19, 17, 21],
       [15, 14, 15, 17],
       [ 9, 10,  9,  8]])

Special Numpy Generators

In [14]:
# generate a list of zeroes
data= np.zeros(5)
data

array([0., 0., 0., 0., 0.])

In [20]:
# another version, this generates
# a matrix 3 x 3 of zeroes
# note: the parameter is now a tuple
data = np.zeros((3, 3))
# we can also generate ones
data = np.ones(5)
# … or a matrix of ones
data = np.ones((4, 4))
# if you want use integer instead of float:
data = np.ones((4, 4))

Even distribution - linspace

In [23]:
# without NumPy, we would have to go
# through an existing collection of data, and
# perform a series of division calculations.
# thanks to NumPy, this can be achieved
# with one line of code
# this one: from 0 to 5, 10 steps
data = np.linspace(0, 5, 5)

Random Array Generations

In [25]:
data = np.random.rand(5)
data

array([0.72226543, 0.8774601 , 0.03539412, 0.43162068, 0.83921029])

In [26]:
# matrix version
data = np.random.rand(5, 5)